### ISSUE TITLE
Add image to body

### ISSUE THREAD

**Issue by TobiSonne** [enricoschumann/mailtools#3]
Is there a way to add an image to my mail body (I only need that for the outlook method and I am using Windows)?
I used `html = TRUE` and added a img-Tag with src and alt but it gave me the error message "Fehler! Es wurde kein Dateiname angegeben."

**Comment by enricoschumann** [comment]
What you could do is link to an image somewhere on the web:
```r
library("mailtools")
sendmail("Image",
         to = "<recipient@somewhere.net>",
         body = "<img src='http://enricoschumann.net/notes/figures/fama-french-1.png' alt='ff3-factors'/>",
         html = TRUE,
         method = "outlook",
         display.only = TRUE)
```

But that is probably not what you want, since the receiving email client will not (should not) display the image straight away. To actually include the image in the message, `sendmail` will have to create a multipart message, which it currently cannot do. I will look into this.

**Comment by enricoschumann** [comment]
Not surprisingly, it is difficult to come up with a method that works for all backends. If you really only care about Windows and Outlook, the following may work:

```r
body <-
"
<html>
<body>
<img src='cid:test.jpg' alt='test.jgp -- see attachments'>
</body>
</html>
"

library("mailtools")
sendmail("TEST",
         body = body,
         to = "test.person@testdomain.net",
         from = "test.person@testdomain.net",
         attach = "/path/to/test.jpg",
         method = "outlook",
         html = TRUE,
         display.only = TRUE)
```

The key is to prefix the image url with `cid` (https://tools.ietf.org/html/rfc2392). I said _may_ work because `mailtools` does not actually create the multipart message, and so there is no guarantee that it is properly constructed. And of course, you don't have any control about the client at the receiving end, which may block attachments or their display altogether. In case the image is not displayed, it is at least available as an attachment.
